### ISSUE TITLE
Pages not loading after trying to goto settings

### ISSUE THREAD

**Issue by ChronoStriker1** [floogulinc/hydrus-web#129]
Using the docker container, on browsers that have not connected to hydrus web before when trying to goto settings nothing loads.
I get this error in the console:
`main.bb19ece846da4239.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'endsWith')
TypeError: Cannot read properties of null (reading 'endsWith')
    at t.getAPIUrl (main.bb19ece846da4239.js:1:472658)
    at t.apiGet (main.bb19ece846da4239.js:1:472835)
    at t.getServices (main.bb19ece846da4239.js:1:475065)
    at new t (main.bb19ece846da4239.js:1:501467)
    at t.ɵfac [as factory] (main.bb19ece846da4239.js:1:501917)
    at O0.hydrate (main.bb19ece846da4239.js:1:44693)
    at O0.get (main.bb19ece846da4239.js:1:43258)
    at F3.get (main.bb19ece846da4239.js:1:68031)
    at qD (main.bb19ece846da4239.js:1:27425)
    at YD (main.bb19ece846da4239.js:1:27899)
    at G (polyfills.a029620566059ce9.js:1:16420)
    at G (polyfills.a029620566059ce9.js:1:15956)
    at polyfills.a029620566059ce9.js:1:17266
    at y.invokeTask (polyfills.a029620566059ce9.js:1:7689)
    at Object.onInvokeTask (main.bb19ece846da4239.js:1:104526)
    at y.invokeTask (polyfills.a029620566059ce9.js:1:7610)
    at I.runTask (polyfills.a029620566059ce9.js:1:3084)
    at L (polyfills.a029620566059ce9.js:1:9689)
    at m.invokeTask [as invoke] (polyfills.a029620566059ce9.js:1:8770)
    at D (polyfills.a029620566059ce9.js:1:20639)`
The only way to get things to load is to manually add the keys
hydrus-web-1_hydrusApiKey and hydrus-web-1_hydrusApiKey to local storage with a value set to them

**Comment by floogulinc** [comment]
Thank you for the report
